
package br.edu.ifrs.restinga.tcc.vrnery.placasws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaPlacasWSService", targetNamespace = "http://service.placasws.vrnery.tcc.restinga.ifrs.edu.br/", wsdlLocation = "http://placasws-vrnery.rhcloud.com/consultaplacaws?wsdl")
public class ConsultaPlacasWSService
    extends Service
{

    private final static URL CONSULTAPLACASWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPLACASWSSERVICE_EXCEPTION;
    private final static QName CONSULTAPLACASWSSERVICE_QNAME = new QName("http://service.placasws.vrnery.tcc.restinga.ifrs.edu.br/", "ConsultaPlacasWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://placasws-vrnery.rhcloud.com/consultaplacaws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPLACASWSSERVICE_WSDL_LOCATION = url;
        CONSULTAPLACASWSSERVICE_EXCEPTION = e;
    }

    public ConsultaPlacasWSService() {
        super(__getWsdlLocation(), CONSULTAPLACASWSSERVICE_QNAME);
    }

    public ConsultaPlacasWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPLACASWSSERVICE_QNAME, features);
    }

    public ConsultaPlacasWSService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPLACASWSSERVICE_QNAME);
    }

    public ConsultaPlacasWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPLACASWSSERVICE_QNAME, features);
    }

    public ConsultaPlacasWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPlacasWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IConsultaPlacasWS
     */
    @WebEndpoint(name = "ConsultaPlacasWSPort")
    public IConsultaPlacasWS getConsultaPlacasWSPort() {
        return super.getPort(new QName("http://service.placasws.vrnery.tcc.restinga.ifrs.edu.br/", "ConsultaPlacasWSPort"), IConsultaPlacasWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IConsultaPlacasWS
     */
    @WebEndpoint(name = "ConsultaPlacasWSPort")
    public IConsultaPlacasWS getConsultaPlacasWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.placasws.vrnery.tcc.restinga.ifrs.edu.br/", "ConsultaPlacasWSPort"), IConsultaPlacasWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPLACASWSSERVICE_EXCEPTION!= null) {
            throw CONSULTAPLACASWSSERVICE_EXCEPTION;
        }
        return CONSULTAPLACASWSSERVICE_WSDL_LOCATION;
    }

}
